### ISSUE TITLE
Topics starting with /

### ISSUE THREAD

**Issue by DirkHeinke** [RangerMauve/mqtt-pattern#3]
It seems like it does not work on topics starting with "/".

```
this.matches("/home","/home")
> false
this.matches("home","home")
> true
```

**Comment by RangerMauve** [comment]
Thank you for the bug report!
I've fixed the issue and added a unit test and I've released it as version 1.1.1.

**Comment by DirkHeinke** [comment]
This was quick! I'm not sure, if the fix is right. I'm no expert, but I would expect the following:
```
/home, /home => true
/home, home => false
home, /home => false
a/b, a//b => false
a//b, a//b => true
```
The only notice I found in [the standard](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718107) is: `Adjacent Topic level separators indicate a zero length topic level.`

**Comment by RangerMauve** [comment]
The changes I added ignore the leading `/` separator in both topics and patterns.

From the [mosquitto man pages](https://mosquitto.org/man/mqtt-7.html) they imply that zero length topics can exist at the beginning or end without affecting the matching.

Specifically they say that ` "/a/topic" would match against a subscription of "+/a/topic", "#" or "/#", and a topic "a/topic/" would match against a subscription of "a/topic/+" or "a/topic/#"`

**Comment by DirkHeinke** [comment]
I understand the mosquitto man pages like this:
```
/a/topic, +/a/topic => true
/a/topic, # => true
/a/topic, /# => true

/a/topic, a/topic => not described, but I would say false

a/topic/, a/topic/+ => true
a/topic/, a/topic/# => true

a/topic//, a/topic/ => also not describe, but again IMHO false
```

Is that how you understand it as well?

**Comment by RangerMauve** [comment]
@DirkHeinke Personally, I disagree with the `/a/topic, a/topic` example.
I believe that if a leading zero length topic level gets ignored when trying to match against a pattern, the same should apply to leading zero length topic levels within patterns.

However, I think the best thing to do here is to see how an actual broker handles this case.

If subscribing on `a/topic` and then publishing `/a/topic` yields no messages in mosquitto then it's safe to say that your interpretation is correct.

Would you be able to test out some of these scenarios on a live broker to see how it handles it?

**Comment by DirkHeinke** [comment]
Yes, I can try it tomorrow and report back.

Am 26.02.2018 22:36 schrieb "RangerMauve" <notifications@github.com>:

**Comment by RangerMauve** [comment]
Awesome! Thanks again for the bug report and debugging. :D

**Comment by DirkHeinke** [comment]
Okay, so here the test results with mosquitto 1.4.14

```
$ mosquitto_sub -t "/a/topic" -d
Client mosqsub|3074-hassbian sending CONNECT
Client mosqsub|3074-hassbian received CONNACK
Client mosqsub|3074-hassbian sending SUBSCRIBE (Mid: 1, Topic: /a/topic, QoS: 0)
Client mosqsub|3074-hassbian received SUBACK
Subscribed (mid: 1): 0
Client mosqsub|3074-hassbian received PUBLISH (d0, q0, r0, m0, '/a/topic', ... (2 bytes))
>>> m1

$ mosquitto_pub -t "/a/topic" -m m1
$ mosquitto_pub -t "a/topic" -m m2

```
/a/topic receives messages to /a/topic but not messages to a/topic

Other way around:
```
$ mosquitto_sub -u dirk -P dirkdirk -t "a/topic" -d
Client mosqsub|3141-hassbian sending CONNECT
Client mosqsub|3141-hassbian received CONNACK
Client mosqsub|3141-hassbian sending SUBSCRIBE (Mid: 1, Topic: a/topic, QoS: 0)
Client mosqsub|3141-hassbian received SUBACK
Subscribed (mid: 1): 0
Client mosqsub|3141-hassbian received PUBLISH (d0, q0, r0, m0, 'a/topic', ... (2 bytes))
>>> m2

$ mosquitto_pub -u dirk -P dirkdirk -t "a/topic" -m m2
$ mosquitto_pub -u dirk -P dirkdirk -t "/a/topic" -m m1
```

a/topic receives messages to a/topic but not message to /a/topic

```
$ mosquitto_sub -t "a/topic//" -d
Client mosqsub|3192-hassbian sending CONNECT
Client mosqsub|3192-hassbian received CONNACK
Client mosqsub|3192-hassbian sending SUBSCRIBE (Mid: 1, Topic: a/topic//, QoS: 0)
Client mosqsub|3192-hassbian received SUBACK
Subscribed (mid: 1): 0
Client mosqsub|3192-hassbian received PUBLISH (d0, q0, r0, m0, 'a/topic//', ... (3 bytes))
>>> m12

$ mosquitto_pub -t "a/topic" -m m10
$ mosquitto_pub -t "a/topic/" -m m11
$ mosquitto_pub -t "a/topic//" -m m12
```
And again:

```
$ mosquitto_sub -t "a/topic" -d
Client mosqsub|3298-hassbian sending CONNECT
Client mosqsub|3298-hassbian received CONNACK
Client mosqsub|3298-hassbian sending SUBSCRIBE (Mid: 1, Topic: a/topic, QoS: 0)
Client mosqsub|3298-hassbian received SUBACK
Subscribed (mid: 1): 0
Client mosqsub|3298-hassbian received PUBLISH (d0, q0, r0, m0, 'a/topic', ... (3 bytes))
>>> m10

$ mosquitto_pub -t "a/topic" -m m10
$ mosquitto_pub -t "a/topic/" -m m11
$ mosquitto_pub -t "a/topic//" -m m12
```

So from what I can see, leading and trailing slashes create different topics. Any other test you would like me to run?

**Comment by RangerMauve** [comment]
Perfect, thank you so much for the details! I'll modify the library to have it behave properly.

**Comment by RangerMauve** [comment]
Try version 1.1.3, I think it should handle zero length topics properly now.

Thanks again for the help with this!

**Comment by DirkHeinke** [comment]
It works perfectly. Thank you very much for your fast update.

**Comment by RangerMauve** [comment]
Any time! Thank you for bringing up the edge case.
